# Generated by Django 4.2 on 2023-04-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(verbose_name='ランキング更新日')),
                ('name', models.CharField(max_length=254, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('average', models.FloatField(verbose_name='レビュー平均点')),
                ('volume', models.IntegerField(verbose_name='レビュー件数')),
                ('rank', models.IntegerField(verbose_name='順位')),
                ('shop_code', models.CharField(max_length=50, verbose_name='ショップコード')),
                ('item_url', models.URLField(verbose_name='商品URL')),
            ],
        ),
    ]
